name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - release
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
      # AM (REMOVE_ACRA_FIREBASE) -->
      # - name: Set ACRA properties
      #  env:
      #    acraUri: ${{ secrets.ACRA_URI }}
      #    acraLogin: ${{ secrets.ACRA_LOGIN }}
      #    acraPassword: ${{ secrets.ACRA_PASSWORD }}
      #  run: |
      #    echo "ACRA_URI=$acraUri" >> acra.properties
      #    echo "ACRA_LOGIN=$acraLogin" >> acra.properties
      #    echo "ACRA_PASSWORD=$acraPassword" >> acra.properties
      # <-- AM (REMOVE_ACRA_FIREBASE)

      - name: Build app and run unit tests
        uses: gradle/gradle-command-action@v2
        with:
          arguments: ktlintCheck assembleStandardRelease testReleaseUnitTest

      # Sign APK and create release for tags

      - name: Get tag name

        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Quickdesh/Animiru'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Quickdesh/Animiru'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/standard/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Quickdesh/Animiru'
        run: |
          set -e

          mv app/build/outputs/apk/standard/release/app-standard-universal-release-unsigned-signed.apk Animiru-universal-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum Animiru-universal-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned-signed.apk Animiru-arm64-v8a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum Animiru-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-armeabi-v7a-release-unsigned-signed.apk Animiru-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum Animiru-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-x86-release-unsigned-signed.apk Animiru-x86-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum Animiru-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-x86_64-release-unsigned-signed.apk Animiru-x86_64-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum Animiru-x86_64-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Quickdesh/Animiru'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Animiru ${{ env.VERSION_TAG }}
          body: |
            ### Changes
            
            - 
            
            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }} |
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }} |
            | universal | ${{ env.APK_UNIVERSAL_SHA }} |
            | x86 | ${{ env.APK_X86_SHA }} |
            | x86_64 | ${{ env.APK_X86_64_SHA }} |
            
            To find out the best version for you:-

            https://play.google.com/store/apps/details?id=ru.andr7e.deviceinfohw

            Download the app from the link above ^

            Open app ---> SOC tab ---> ABI/Supported ABI

            Install based on the values given in the above variant fields

            Universal will work regardless of the ABI

          files: |
            Animiru-universal-${{ env.VERSION_TAG }}.apk
            Animiru-arm64-v8a-${{ env.VERSION_TAG }}.apk
            Animiru-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            Animiru-x86-${{ env.VERSION_TAG }}.apk
            Animiru-x86_64-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
